server:
  port: ${SERVICE_PORT:9090}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_IP:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    ip-address: ${HOST_IP:localhost}
    prefer-ip-address: true

spring:
  application:
    name: frontend

logging:
  path: /var/log/
  file: frontend-service.log
