server:
  port: ${SERVICE_PORT:9090}

spring:
  application:
    name: frontend

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_IP:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    ip-address: ${HOST_IP:localhost}
    prefer-ip-address: true
    metadataMap:
      instanceId: ${spring.application.name}:${SERVICE_PORT:9090}

logging:
  path: /var/log/
  file: frontend-service.log
