server:
  port: ${SERVICE_PORT:10000}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_IP:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    ip-address: ${HOST_IP:localhost}
    prefer-ip-address: true

spring:
  application:
    name: api-gateway
    
logging:
  path: /var/log/
  file: api_gateway.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}] [%15.15t] %-40.40logger{39}: %m%n'
