server:
  port: ${SERVICE_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_IP}:${EUREKA_PORT}/eureka/
  instance:
    ip-address: ${HOST_IP}
    prefer-ip-address: true

spring:
  application:
    name: images
